### ISSUE TITLE
Mirrors down?

### ISSUE THREAD

**Issue by rapzo** [erikogan/passenger#10]
Hi!

Awesome work you're doing here!
Although, i tried to update the passenger in Fedora 15 (tweaked the passenger for F14 in order to work with F15) but i always get this error:
Error: Cannot retrieve repository metadata (repomd.xml) for repository: passenger. Please verify its path and try again

Keep up the good work.

**Comment by erikogan** [comment]
I'm not sure what you tweaked, but it appears it was still attempting to pull from the F15 repository. That should have been ok, since they're there (as of a few weeks ago). However, the repository metadata appears to have gone missing in promoting that release to live.

Thanks for the heads-up, it's now fixed.

**Comment by rapzo** [comment]
Not much, just some SEL rules and libev3, since libev4 was not compatible.
Well, but everything is fixed now!
Thanks again!
