### ISSUE TITLE
dependency on Amazon Linux

### ISSUE THREAD

**Issue by neoandroid** [erikogan/passenger#8]
Hi Erik,

In the SPEC file of the rpm we can see the following code:

%if %{?fedora:1}%{?!fedora:0}
BuildRequires: perl-ExtUtils-Embed
BuildRequires: libcurl-devel
BuildRequires: source-highlight
%else
BuildRequires: curl-devel
%endif

Unfortunately on Amazon Linux the packet curl-devel is called libcurl-devel as is on Fedora.
Can you adapt the SPEC so the package can be build and installed also on Amazon Linux?.
As a workaround we changed the code with the one below, but it won't work well for Fedora.

%if %{?fedora:1}%{?!fedora:0}
BuildRequires: perl-ExtUtils-Embed
BuildRequires: libcurl-devel
BuildRequires: source-highlight
%endif
%if %{?amzn:1}%{?!amzn:0}
BuildRequires: libcurl-devel
%else
BuildRequires: curl-devel
%endif

If you need help on testing on Amazon EC2 platform ask me and I will test what you need.
- Jordi

**Comment by erikogan** [comment]
Sorry for the delay, your request was buried inside a deluge of work-related requests. (And I don't seem to have gotten email with it as well, so I didn't know to look. Hrm…)

I reworked most of those conditionals last night and this morning getting things to build on CentOS 6. We should probably look them all over for Amazon Linux, since it seems to be an amalgam of CentOS5 & 6. One of the big questions there: does an EC2 box have libev? (Most of the conditionals are about the vendored version of libev)

**Comment by erikogan** [comment]
I've pushed a modification that also checks for the %amzn macro when testing for el5 (since it's now the legacy exception for most places where things differ.)

Provided Amazon Linux already has a package for libev (which it seems like it would) that should fix the matter. Let me know if you have any further problems, and we can collaborate on solutions.

**Comment by erikogan** [comment]
So I fired up an EC2 instance, and it looks like libev isn't available (it’s neither preinstalled, nor in the yum repository). I just pushed a fix that should address that.

Please let me know if you need any additional assistance, and yes, I'd love to have you help test on EC2!

**Comment by neoandroid** [comment]
Sorry, I've been busy last weeks with other jobs and I couldn't spend time on this. Finally, I've tested it on Wednesday until today and it seems that works fine. Good job.
I've built RPM's from SPEC file in 32 bit and 64 bit Amazon Linux and it compiles correctly producing working packages.

**Comment by erikogan** [comment]
That is good news! 

Wednesday I was working on pushing out the 3.0.8-1 packages, did you by chance pick up those changes?
